# Copyright (c) 2024 Nordic Semiconductor
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

manifest:
  self:
    west-commands: scripts/west-commands.yml
    path: project

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: gide-remote
      url-base: https://github.com/DematteisGiacomo

  projects:
    - name: nrf
      remote:  gide-remote
      repo-path: sdk-nrf
      revision: lte_lc_send_cereg_always
      import: true
