# Copyright (c) 2024 Nordic Semiconductor
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

manifest:
  self:
    west-commands: scripts/west-commands.yml
    path: project

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: memfault
      url-base: https://github.com/memfault

  projects:
    - name: nrf
      remote: ncs
      repo-path: sdk-nrf
      revision: 3896aa0dab64db191e51d077313abf27ac70f05c
      import: true

    - name: memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      revision: 1.27.0
      remote: memfault
