# Copyright (c) 2024 Nordic Semiconductor
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

manifest:
  self:
    west-commands: scripts/west-commands.yml
    path: project

  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
    - name: ntn-fork-nrf-sdk
      url-base: https://github.com/DematteisGiacomo

  projects:
    - name: nrf
      remote: ntn-fork-nrf-sdk
      repo-path: sdk-nrf
      revision: ntn_gnss_usecase
      import: true
