/*
 * Copyright (c) 2026 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#include <errno.h>
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>
#include <zephyr/random/random.h>
#include <zephyr/sys/util.h>
#include <app_jwt.h>

LOG_MODULE_DECLARE(cloud, CONFIG_APP_CLOUD_LOG_LEVEL);

/* Hardware type prefix of the iss and jti claims, as in JWTs generated by the modem */
#define JWT_HW_TYPE "nRF9251"
#define JTI_RANDOM_BYTES 8

/* nRF Cloud Provisioning authenticates the device with a JWT that it generates with
 * modem_jwt_generate(), which uses AT%JWT to sign it with the modem's device identity key.
 * On nRF92 Series devices, the application core and the modem have separate identities,
 * and the device is claimed with an attestation token from the application core.
 * Replace the function with one that signs the JWT with the application IAK instead,
 * using the application core UUID as the subject.
 */
int __wrap_nrf_provisioning_jwt_generate(uint32_t time_valid_s, char *const jwt_buf,
					 size_t jwt_buf_sz)
{
	char uuid[APP_JWT_UUID_V4_STR_LEN];
	char issuer[APP_JWT_CLAIM_MAX_SIZE];
	char jti[APP_JWT_CLAIM_MAX_SIZE];
	uint8_t random[JTI_RANDOM_BYTES];
	char random_hex[(JTI_RANDOM_BYTES * 2) + 1];
	int err;

	if (!jwt_buf || !jwt_buf_sz) {
		return -EINVAL;
	}

	err = app_jwt_get_uuid(uuid, sizeof(uuid));
	if (err) {
		LOG_ERR("app_jwt_get_uuid, error: %d", err);
		return err;
	}

	sys_rand_get(random, sizeof(random));
	bin2hex(random, sizeof(random), random_hex, sizeof(random_hex));

	snprintk(issuer, sizeof(issuer), JWT_HW_TYPE ".%s", uuid);
	snprintk(jti, sizeof(jti), JWT_HW_TYPE ".%s.%s", uuid, random_hex);

	if ((time_valid_s == 0) || (time_valid_s > CONFIG_NRF_PROVISIONING_JWT_MAX_VALID_TIME_S)) {
		time_valid_s = CONFIG_NRF_PROVISIONING_JWT_MAX_VALID_TIME_S;
	}

	struct app_jwt_data jwt = {
		/* sec_tag 0 selects the application IAK */
		.sec_tag = 0,
		.key_type = JWT_KEY_TYPE_CLIENT_PRIV,
		.alg = JWT_ALG_TYPE_ES256,
		.add_keyid_to_header = true,
		.json_token_id = jti,
		.subject = uuid,
		.issuer = issuer,
		.add_timestamp = true,
		.validity_s = time_valid_s,
		.jwt_buf = jwt_buf,
		.jwt_sz = jwt_buf_sz,
	};

	LOG_DBG("Generating JWT for %s", uuid);

	err = app_jwt_generate(&jwt);
	if (err) {
		LOG_ERR("app_jwt_generate, error: %d", err);
	}

	return err;
}
