#
# Copyright (c) 2025 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

CONFIG_MEMFAULT=y
CONFIG_MEMFAULT_HEAP_STATS=y
CONFIG_MEMFAULT_LOGGING_ENABLE=y
CONFIG_MEMFAULT_LOGGING_RAM_SIZE=3584
CONFIG_MEMFAULT_FS_BYTES_FREE_METRIC=n
CONFIG_MEMFAULT_COREDUMP_FULL_THREAD_STACKS=y
CONFIG_MEMFAULT_EVENT_STORAGE_SIZE=4096
CONFIG_PM_PARTITION_SIZE_MEMFAULT_STORAGE=0x2A000
CONFIG_MEMFAULT_COREDUMP_COLLECT_BSS_REGIONS=y

# Use CoAP for Memfault data transport
CONFIG_MEMFAULT_USE_NRF_CLOUD_COAP=y
CONFIG_MEMFAULT_HTTP_ENABLE=n
CONFIG_NRF_CLOUD_COAP_MAX_USER_OPTIONS=2
CONFIG_COAP_CLIENT_MAX_EXTRA_OPTIONS=3

# Increase max post size to maximum allowable to improve upload efficiency.
# This value is calculated from:
# (COAP_CLIENT_MESSAGE_SIZE + COAP_CLIENT_MESSAGE_HEADER_SIZE - 100B options overhead).
CONFIG_MEMFAULT_COAP_MAX_POST_SIZE=972

# Set max number of messages to send in one batch to max allowable to support
# uploading flash-backed coredumps and modem traces in one upload attempt.
#
# Note: Sending all available data will not block other tasks since upload
# always occurs in a dedicated thread (either via mflt_lte_coredump_thread when
# CONFIG_MEMFAULT_NCS_POST_COREDUMP_ON_NETWORK_CONNECTED is enabled or via
# CONFIG_MEMFAULT_PERIODIC_UPLOAD_USE_DEDICATED_WORKQUEUE which is default y).
CONFIG_MEMFAULT_COAP_MAX_MESSAGES_TO_SEND=10000

# Certificate management
CONFIG_MEMFAULT_ROOT_CERT_STORAGE_NRF9160_MODEM=y
CONFIG_MODEM_KEY_MGMT=y

# Memfault NCS integration
CONFIG_MEMFAULT_NCS_LTE_METRICS=y
CONFIG_MEMFAULT_NCS_STACK_METRICS=y
CONFIG_MEMFAULT_NCS_INTERNAL_FLASH_BACKED_COREDUMP=y
CONFIG_MEMFAULT_NCS_POST_COREDUMP_ON_NETWORK_CONNECTED=y
CONFIG_MEMFAULT_NCS_POST_COREDUMP_RETRIES_MAX=10
CONFIG_MEMFAULT_NCS_FW_TYPE="att"

# Ensure Memfault device id matches nRF Cloud client id
CONFIG_MEMFAULT_NCS_DEVICE_ID_HW_ID=y
CONFIG_HW_ID_LIBRARY_SOURCE_UUID=y

# Memfault depends on POSIX, disable unneeded POSIX features
CONFIG_POSIX_FILE_SYSTEM=n
