#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Myriota HyperPulse backend
CONFIG_APP_NTN_BACKEND_MYRIOTA=y
CONFIG_HYPERPULSE=y
CONFIG_HYPERPULSE_AUTO_LIB_INIT=y

# Disable Nordic NTN library (not used with HyperPulse)
CONFIG_NTN=n

# Include GNSS coordinates in the default uplink payload
CONFIG_APP_NTN_SEND_GNSS_DATA=y

# HyperPulse storage partition size for ZMS
CONFIG_PM_PARTITION_SIZE_ZMS_STORAGE=0
