#
# Copyright (c) 2026 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# PDN configuration for Iridium SIM card
CONFIG_LTE_LC_PDN_DEFAULTS_OVERRIDE=y
CONFIG_LTE_LC_PDN_DEFAULT_FAM_IPV4=y
CONFIG_LTE_LC_PDN_DEFAULT_APN="iot"

CONFIG_APP_NTN_IRIDIUM=y
CONFIG_APP_NTN_BANDLOCK_ENABLE=y
CONFIG_APP_NTN_BANDLOCK=249
CONFIG_APP_NTN_CHANNEL_SELECT_ENABLE=y
CONFIG_APP_NTN_CHANNEL_SELECT=196702
