## Addition App specific Kconfigs to make softsim work with ATT

# CONFIG_NRF_CLOUD_SEND_SERVICE_INFO_FOTA=y
# CONFIG_BOOTLOADER_MCUBOOT=y
# CONFIG_IMG_MANAGER=y
# CONFIG_MCUBOOT_IMG_MANAGER=y
# CONFIG_STREAM_FLASH_ERASE=y

# CONFIG_DOWNLOADER=y
# CONFIG_DOWNLOADER_STACK_SIZE=1664


# CONFIG_FLASH=y
# CONFIG_FLASH_PAGE_LAYOUT=y
# CONFIG_FLASH_MAP=y
# CONFIG_STREAM_FLASH=y
# CONFIG_MPU_ALLOW_FLASH_WRITE=y
# CONFIG_NRF_CLOUD_LOG_DIRECT=n
# CONFIG_NRF_CLOUD_LOG_OUTPUT_LEVEL=3
# CONFIG_NRF_CLOUD_FOTA_POLL=y
# CONFIG_NRF_CLOUD_FOTA_POLL_LOG_LEVEL_DBG=y
# CONFIG_NRF_CLOUD_FOTA_FULL_MODEM_UPDATE=y
# CONFIG_NRF_CLOUD_FOTA_DOWNLOAD_FRAGMENT_SIZE=1900
# CONFIG_NRF_CLOUD_COAP_DOWNLOADS=y
# CONFIG_FOTA_DOWNLOAD=y
# CONFIG_FOTA_DOWNLOAD_PROGRESS_EVT=y
# CONFIG_FOTA_DL_TIMEOUT_MIN=60
# CONFIG_FOTA_SOCKET_RETRIES=5
# CONFIG_DFU_TARGET=y


# CONFIG_PICOLIBC=y
