#
# Copyright (c) 2026 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# Enable richer diagnostics and more optimal upload behavior for Memfault.
#

CONFIG_MEMFAULT_HEAP_STATS=y
CONFIG_MEMFAULT_EVENT_STORAGE_SIZE=4096
CONFIG_MEMFAULT_LOGGING_RAM_SIZE=3584
CONFIG_MEMFAULT_NCS_POST_COREDUMP_ON_NETWORK_CONNECTED=y
CONFIG_MEMFAULT_NCS_POST_COREDUMP_RETRIES_MAX=10
CONFIG_MEMFAULT_PERIODIC_UPLOAD_USE_DEDICATED_WORKQUEUE=y
CONFIG_PM_PARTITION_SIZE_MEMFAULT_STORAGE=0x2A000
