#
# Copyright (c) 2025 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Extra configuration for Sateliot
CONFIG_LTE_LC_PDN_DEFAULTS_OVERRIDE=n
CONFIG_LTE_LC_PDN_DEFAULT_FAM_IPV4=n
CONFIG_LTE_LC_PDN_DEFAULT_APN=""

CONFIG_APP_NTN_CHANNEL_SELECT_ENABLE=y
# Finland/Norway
CONFIG_APP_NTN_CHANNEL_SELECT=229236
# Barcelona
#CONFIG_APP_NTN_CHANNEL_SELECT=229312
# Brazil
#CONFIG_APP_NTN_CHANNEL_SELECT=229232
# Australia
#CONFIG_APP_NTN_CHANNEL_SELECT=229336
