#
# Copyright (c) 2025 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
# Board overlay for Myriota NTN builds on nRF9151 DK.

CONFIG_SPI=n
CONFIG_SPI_NOR=n
CONFIG_PM_OVERRIDE_EXTERNAL_DRIVER_CHECK=n
