@startuml
state STATE_RUNNING {
    [*] --> STATE_DISCONNECTED

    state STATE_DISCONNECTED
    state STATE_CONNECTING
    state STATE_CONNECTED

    STATE_DISCONNECTED --> STATE_CONNECTING : NETWORK_CONNECTED

    state STATE_CONNECTING {
        [*] --> STATE_CONNECTING_ATTEMPT

        state STATE_CONNECTING_ATTEMPT {
            [*] --> STATE_PROVISIONED

            STATE_PROVISIONED --> STATE_PROVISIONING : CLOUD_NOT_AUTHENTICATED
            STATE_PROVISIONED --> STATE_CONNECTED : CLOUD_CONNECTION_SUCCESS
            STATE_PROVISIONED --> STATE_CONNECTING_BACKOFF : CLOUD_CONNECTION_FAILED
        }

        STATE_CONNECTING --> STATE_DISCONNECTED : NETWORK_DISCONNECTED
        STATE_PROVISIONING --> STATE_PROVISIONED : CLOUD_PROVISIONING_FINISHED
        STATE_PROVISIONING --> STATE_CONNECTING_BACKOFF : CLOUD_PROVISIONING_FAILED && network_connected
        STATE_PROVISIONING --> STATE_DISCONNECTED : CLOUD_PROVISIONING_FAILED && !network_connected
        STATE_CONNECTING_BACKOFF --> STATE_PROVISIONED : CLOUD_BACKOFF_EXPIRED && !provisioning_ongoing
        STATE_CONNECTING_BACKOFF --> STATE_PROVISIONING : CLOUD_BACKOFF_EXPIRED && provisioning_ongoing
    }

    state STATE_CONNECTED {
        [*] --> STATE_CONNECTED_READY

        STATE_CONNECTED_READY --> STATE_CONNECTED_PAUSED : NETWORK_DISCONNECTED
        STATE_CONNECTED_READY --> STATE_CONNECTING : CLOUD_SEND_REQUEST_FAILED
        STATE_CONNECTED_READY --> STATE_PROVISIONING : CLOUD_PROVISIONING_REQUEST
        STATE_CONNECTED_PAUSED --> STATE_CONNECTED_READY : NETWORK_CONNECTED
    }
}

[*] --> STATE_RUNNING
@enduml
