@startuml

state STATE_RUNNING{

    state STATE_DISCONNECTED {
        STATE_DISCONNECTED : entry / publish CLOUD_DISCONNECTED
        STATE_DISCONNECTED --> STATE_CONNECTING : NETWORK_CONNECTED
    }

    state STATE_CONNECTING {

        state STATE_CONNECTING_ATTEMPT {

            state STATE_PROVISIONED {
                STATE_PROVISIONED : entry / connect_to_cloud()
                STATE_PROVISIONED --> STATE_PROVISIONING : CLOUD_NOT_AUTHENTICATED
                STATE_PROVISIONED --> STATE_CONNECTED : CLOUD_CONNECTION_SUCCESS
                STATE_PROVISIONED --> STATE_CONNECTING_BACKOFF : CLOUD_CONNECTION_FAILED
            }

            state STATE_PROVISIONING {
                STATE_PROVISIONING : NETWORK_CONNECTED / ;
                STATE_PROVISIONING : NETWORK_DISCONNECTED / ;
                STATE_PROVISIONING --> STATE_PROVISIONED : CLOUD_PROVISIONING_FINISHED / send_provisioned_msg()
                STATE_PROVISIONING --> STATE_CONNECTING_BACKOFF : CLOUD_PROVISIONING_FAILED && network_connected
                STATE_PROVISIONING --> STATE_DISCONNECTED : CLOUD_PROVISIONING_FAILED && !network_connected

            }

            [*] --> STATE_PROVISIONED

            STATE_CONNECTING --> STATE_DISCONNECTED : NETWORK_DISCONNECTED

        }

        state STATE_CONNECTING_BACKOFF {
            STATE_CONNECTING_BACKOFF --> STATE_PROVISIONED : CLOUD_BACKOFF_EXPIRED && !provisioning_ongoing
            STATE_CONNECTING_BACKOFF --> STATE_PROVISIONING : CLOUD_BACKOFF_EXPIRED && provisioning_ongoing
        }

        [*] --> STATE_CONNECTING_ATTEMPT

    }

    state STATE_CONNECTED {

        state STATE_CONNECTED_READY {
            STATE_CONNECTED_READY : entry / publish CLOUD_CONNECTED
            STATE_CONNECTED_READY : NETWORK_CONNECTED / ;
            STATE_CONNECTED_READY : STORAGE_BATCH_AVAILABLE / handle_storage_batch_available()
            STATE_CONNECTED_READY : STORAGE_BATCH_EMPTY / handle_storage_batch_empty()
            STATE_CONNECTED_READY : STORAGE_BATCH_ERROR / handle_storage_batch_error()
            STATE_CONNECTED_READY : STORAGE_BATCH_BUSY / handle_storage_batch_busy()
            STATE_CONNECTED_READY : STORAGE_DATA / handle_storage_data()
            STATE_CONNECTED_READY : CLOUD_PAYLOAD_JSON / nrf_cloud_coap_json_message_send()
            STATE_CONNECTED_READY : CLOUD_SHADOW_GET_DELTA / cloud_configuration_poll(SHADOW_POLL_DELTA)
            STATE_CONNECTED_READY : CLOUD_SHADOW_GET_DESIRED / cloud_configuration_poll(SHADOW_POLL_DESIRED)
            STATE_CONNECTED_READY : CLOUD_SHADOW_SET_REPORTED_CONFIG / cloud_configuration_reported_set()
            STATE_CONNECTED_READY : CLOUD_SHADOW_UPDATE_REPORTED_CONFIG / cloud_configuration_reported_update()
            STATE_CONNECTED_READY : CLOUD_SHADOW_UPDATE_REPORTED_DEVICE / nrf_cloud_coap_shadow_configured_info_update()
            STATE_CONNECTED_READY : LOCATION_AGNSS_REQUEST / cloud_location_handle_message() [CONFIG_APP_LOCATION]
            STATE_CONNECTED_READY --> STATE_CONNECTED_PAUSED : NETWORK_DISCONNECTED
            STATE_CONNECTED_READY --> STATE_CONNECTING : PRIV_CLOUD_CHAN(CLOUD_SEND_REQUEST_FAILED)
            STATE_CONNECTED_READY --> STATE_PROVISIONING : CLOUD_PROVISIONING_REQUEST
        }

        state STATE_CONNECTED_PAUSED {
            STATE_CONNECTED_PAUSED --> STATE_CONNECTED_READY : NETWORK_CONNECTED
        }

        [*] --> STATE_CONNECTED_READY

    }

    [*] --> STATE_DISCONNECTED

}

[*] --> STATE_RUNNING
@enduml
