@startuml

state STATE_RUNNING{

    state STATE_DISCONNECTED{
        STATE_DISCONNECTED : entry / publish CLOUD_DISCONNECTED
    }
    state STATE_CONNECTING{

        state STATE_CONNECTING_ATTEMPT{

            state STATE_PROVISIONED{
                STATE_PROVISIONED : entry / connect_to_cloud()
            }
            state STATE_PROVISIONING{
                STATE_PROVISIONING : NETWORK_CONNECTED / ;
                STATE_PROVISIONING : NETWORK_DISCONNECTED / ;
            }

            [*] --> STATE_PROVISIONED
            STATE_PROVISIONED --> STATE_PROVISIONING : CLOUD_NOT_AUTHENTICATED
            STATE_PROVISIONED --> STATE_CONNECTED : CLOUD_CONNECTION_SUCCESS
            STATE_PROVISIONED --> STATE_CONNECTING_BACKOFF : CLOUD_CONNECTION_FAILED

            STATE_PROVISIONING --> STATE_PROVISIONED : CLOUD_PROVISIONING_FINISHED
            STATE_PROVISIONING --> STATE_CONNECTING_BACKOFF : CLOUD_PROVISIONING_FAILED && network_connected
            STATE_PROVISIONING --> STATE_DISCONNECTED : CLOUD_PROVISIONING_FAILED && !network_connected
        }
        state STATE_CONNECTING_BACKOFF{
        }

        [*] --> STATE_CONNECTING_ATTEMPT
        STATE_CONNECTING_BACKOFF --> STATE_PROVISIONED : CLOUD_BACKOFF_EXPIRED && !provisioning_ongoing
        STATE_CONNECTING_BACKOFF --> STATE_PROVISIONING : CLOUD_BACKOFF_EXPIRED && provisioning_ongoing
    }
    state STATE_CONNECTED{

        state STATE_CONNECTED_READY
        state STATE_CONNECTED_PAUSED

        [*] --> STATE_CONNECTED_READY
        STATE_CONNECTED_READY --> STATE_CONNECTED_PAUSED : NETWORK_DISCONNECTED
        STATE_CONNECTED_READY --> STATE_CONNECTING : PRIV_CLOUD_CHAN(CLOUD_SEND_REQUEST_FAILED)
        STATE_CONNECTED_READY --> STATE_PROVISIONING : CLOUD_PROVISIONING_REQUEST
        STATE_CONNECTED_PAUSED --> STATE_CONNECTED_READY : NETWORK_CONNECTED
    }
    [*] --> STATE_DISCONNECTED
    STATE_DISCONNECTED --> STATE_CONNECTING : NETWORK_CONNECTED
    STATE_CONNECTING --> STATE_DISCONNECTED : NETWORK_DISCONNECTED
}
[*] --> STATE_RUNNING
@enduml
