@startuml
state STATE_RUNNING {
    [*] --> STATE_DISCONNECTED

    state STATE_DISCONNECTED
    state STATE_CONNECTING {
        [*] --> STATE_CONNECTING_ATTEMPT
        state STATE_CONNECTING_ATTEMPT
        state STATE_CONNECTING_BACKOFF

        STATE_CONNECTING_ATTEMPT --> STATE_CONNECTING_BACKOFF: CLOUD_CONNECTION_ATTEMPTED
        STATE_CONNECTING_BACKOFF --> STATE_CONNECTING_ATTEMPT: CLOUD_BACKOFF_EXPIRED
    }
    state STATE_CONNECTED

    STATE_DISCONNECTED --> STATE_CONNECTING: NETWORK_CONNECTED
    STATE_CONNECTING --> STATE_CONNECTED: CLOUD_CONNECTED
    STATE_CONNECTED --> STATE_CONNECTING: CLOUD_DISCONNECTED
}

[*] --> STATE_RUNNING
STATE_RUNNING --> STATE_DISCONNECTED: NETWORK_DISCONNECTED
@enduml