@startuml
state STATE_RUNNING

[*] --> STATE_RUNNING

STATE_RUNNING --> STATE_CANCELING: FOTA_DOWNLOAD_CANCEL

state STATE_RUNNING {
    state STATE_WAITING_FOR_POLL_REQUEST {
        STATE_WAITING_FOR_POLL_REQUEST : FOTA_DOWNLOAD_CANCEL /
    }
    state STATE_POLLING_FOR_UPDATE {
        STATE_POLLING_FOR_UPDATE : entry / nrf_cloud_fota_poll_process()
        STATE_POLLING_FOR_UPDATE : FOTA_DOWNLOAD_CANCEL /
    }
    state STATE_DOWNLOADING_UPDATE
    state STATE_WAITING_FOR_IMAGE_APPLY
    state STATE_IMAGE_APPLYING
    state STATE_REBOOT_PENDING
    state STATE_CANCELING

    [*] --> STATE_WAITING_FOR_POLL_REQUEST

    STATE_WAITING_FOR_POLL_REQUEST --> STATE_POLLING_FOR_UPDATE: FOTA_POLL_REQUEST

    STATE_POLLING_FOR_UPDATE --> STATE_DOWNLOADING_UPDATE: FOTA_DOWNLOADING_UPDATE
    STATE_POLLING_FOR_UPDATE --> STATE_WAITING_FOR_POLL_REQUEST: FOTA_NO_AVAILABLE_UPDATE

    STATE_DOWNLOADING_UPDATE --> STATE_WAITING_FOR_IMAGE_APPLY: FOTA_IMAGE_APPLY_NEEDED
    STATE_DOWNLOADING_UPDATE --> STATE_REBOOT_PENDING: FOTA_SUCCESS_REBOOT_NEEDED
    STATE_DOWNLOADING_UPDATE --> STATE_WAITING_FOR_POLL_REQUEST: FOTA_DOWNLOAD_CANCELED || FOTA_DOWNLOAD_TIMED_OUT || FOTA_DOWNLOAD_FAILED || FOTA_DOWNLOAD_REJECTED

    STATE_WAITING_FOR_IMAGE_APPLY --> STATE_IMAGE_APPLYING: FOTA_IMAGE_APPLY

    STATE_IMAGE_APPLYING --> STATE_REBOOT_PENDING: FOTA_SUCCESS_REBOOT_NEEDED

    STATE_CANCELING --> STATE_WAITING_FOR_POLL_REQUEST: FOTA_DOWNLOAD_CANCELED
}
@enduml
