@startuml
state STATE_RUNNING {
    state STATE_LOCATION_SEARCH_INACTIVE
    state STATE_LOCATION_SEARCH_ACTIVE

    [*] --> STATE_LOCATION_SEARCH_INACTIVE

    STATE_LOCATION_SEARCH_INACTIVE --> STATE_LOCATION_SEARCH_ACTIVE: LOCATION_SEARCH_TRIGGER
    STATE_LOCATION_SEARCH_ACTIVE --> STATE_LOCATION_SEARCH_INACTIVE: LOCATION_SEARCH_DONE
}

[*] --> STATE_RUNNING
@enduml
