@startuml

[*] --> STATE_RUNNING
STATE_RUNNING --> STATE_FOTA: FOTA_DOWNLOADING_UPDATE
STATE_FOTA --> STATE_RUNNING[H*]: FOTA_DOWNLOAD_CANCELED || FOTA_DOWNLOAD_TIMED_OUT || FOTA_DOWNLOAD_FAILED || FOTA_DOWNLOAD_REJECTED

state STATE_RUNNING {

    [*] --> STATE_PASSTHROUGH_MODE : CONFIG_APP_STORAGE_INITIAL_MODE_PASSTHROUGH
    [*] --> STATE_BUFFER_MODE : not CONFIG_APP_STORAGE_INITIAL_MODE_PASSTHROUGH

    state STATE_BUFFER_MODE {
        [*] --> STATE_BUFFER_DISCONNECTED

        state STATE_BUFFER_DISCONNECTED {
            [*] --> STATE_BUFFER_DISCONNECTED_SAMPLING
            state STATE_BUFFER_DISCONNECTED_SAMPLING
            state STATE_BUFFER_DISCONNECTED_WAITING

            STATE_BUFFER_DISCONNECTED_SAMPLING --> STATE_BUFFER_DISCONNECTED_WAITING: LOCATION_SEARCH_DONE
            STATE_BUFFER_DISCONNECTED_WAITING --> STATE_BUFFER_DISCONNECTED_SAMPLING: TIMER_EXPIRED_SAMPLE_DATA || BUTTON_PRESS_SHORT
            STATE_BUFFER_DISCONNECTED_WAITING --> STATE_BUFFER_DISCONNECTED_WAITING: TIMER_CONFIG_CHANGED
        }

        state STATE_BUFFER_CONNECTED {
            [*] --> STATE_BUFFER_CONNECTED_SAMPLING
            state STATE_BUFFER_CONNECTED_SAMPLING
            state STATE_BUFFER_CONNECTED_WAITING

            STATE_BUFFER_CONNECTED_SAMPLING --> STATE_BUFFER_CONNECTED_WAITING: LOCATION_SEARCH_DONE
            STATE_BUFFER_CONNECTED_WAITING --> STATE_BUFFER_CONNECTED_SAMPLING: TIMER_EXPIRED_SAMPLE_DATA || BUTTON_PRESS_SHORT
            STATE_BUFFER_CONNECTED_WAITING --> STATE_BUFFER_CONNECTED_WAITING: TIMER_CONFIG_CHANGED
        }

        STATE_BUFFER_DISCONNECTED --> STATE_BUFFER_CONNECTED: CLOUD_CONNECTED
        STATE_BUFFER_DISCONNECTED --> STATE_PASSTHROUGH_DISCONNECTED: STORAGE_MODE_PASSTHROUGH
        STATE_BUFFER_CONNECTED --> STATE_BUFFER_DISCONNECTED: CLOUD_DISCONNECTED
        STATE_BUFFER_CONNECTED --> STATE_PASSTHROUGH_CONNECTED: STORAGE_MODE_PASSTHROUGH
    }

    state STATE_PASSTHROUGH_MODE {
        [*] --> STATE_PASSTHROUGH_DISCONNECTED

        state STATE_PASSTHROUGH_CONNECTED
        state STATE_PASSTHROUGH_DISCONNECTED

        state STATE_PASSTHROUGH_CONNECTED {
            [*] --> STATE_PASSTHROUGH_CONNECTED_SAMPLING
            state STATE_PASSTHROUGH_CONNECTED_SAMPLING
            state STATE_PASSTHROUGH_CONNECTED_WAITING

            STATE_PASSTHROUGH_CONNECTED_SAMPLING --> STATE_PASSTHROUGH_CONNECTED_WAITING: LOCATION_SEARCH_DONE
            STATE_PASSTHROUGH_CONNECTED_WAITING --> STATE_PASSTHROUGH_CONNECTED_SAMPLING: TIMER_EXPIRED_SAMPLE_DATA || BUTTON_PRESS_SHORT
            STATE_PASSTHROUGH_CONNECTED_WAITING --> STATE_PASSTHROUGH_CONNECTED_WAITING: TIMER_CONFIG_CHANGED
        }

        STATE_PASSTHROUGH_DISCONNECTED --> STATE_PASSTHROUGH_CONNECTED_SAMPLING: CLOUD_CONNECTED
        STATE_PASSTHROUGH_DISCONNECTED --> STATE_BUFFER_DISCONNECTED: STORAGE_MODE_BUFFER
        STATE_PASSTHROUGH_CONNECTED --> STATE_BUFFER_CONNECTED: STORAGE_MODE_BUFFER
    }

    STATE_PASSTHROUGH_MODE --> STATE_PASSTHROUGH_DISCONNECTED: CLOUD_DISCONNECTED
    STATE_PASSTHROUGH_MODE --> STATE_PASSTHROUGH_CONNECTED_SAMPLING: CLOUD_CONNECTED
}

state STATE_FOTA {
    [*] --> STATE_FOTA_DOWNLOADING

    state STATE_FOTA_DOWNLOADING
    state STATE_FOTA_WAITING_FOR_NETWORK_DISCONNECT
    state STATE_FOTA_WAITING_FOR_NETWORK_DISCONNECT_TO_APPLY_IMAGE
    state STATE_FOTA_APPLYING_IMAGE
    state STATE_FOTA_REBOOTING

    STATE_FOTA_DOWNLOADING --> STATE_FOTA_WAITING_FOR_NETWORK_DISCONNECT: FOTA_SUCCESS_REBOOT_NEEDED
    STATE_FOTA_DOWNLOADING --> STATE_FOTA_WAITING_FOR_NETWORK_DISCONNECT_TO_APPLY_IMAGE: FOTA_IMAGE_APPLY_NEEDED
    STATE_FOTA_WAITING_FOR_NETWORK_DISCONNECT --> STATE_FOTA_REBOOTING: NETWORK_DISCONNECTED
    STATE_FOTA_WAITING_FOR_NETWORK_DISCONNECT_TO_APPLY_IMAGE --> STATE_FOTA_APPLYING_IMAGE: NETWORK_DISCONNECTED
    STATE_FOTA_APPLYING_IMAGE --> STATE_FOTA_REBOOTING: FOTA_SUCCESS_REBOOT_NEEDED
}

@enduml
