@startuml

[*] --> STATE_RUNNING

state STATE_RUNNING {
    [*] --> STATE_DISCONNECTED

    STATE_RUNNING --> STATE_DISCONNECTED: NETWORK_DISCONNECTED
    STATE_RUNNING --> STATE_DISCONNECTED_IDLE: NETWORK_UICC_FAILURE

    state STATE_DISCONNECTED {
        [*] --> STATE_DISCONNECTED_IDLE

        STATE_DISCONNECTED --> STATE_DISCONNECTED_IDLE: NETWORK_DISCONNECT / network_disconnect()
        STATE_DISCONNECTED --> STATE_DISCONNECTED_NTN_SEARCH: LEO_SATELLITE_PASS_UPCOMING / network_disconnect()
        STATE_DISCONNECTED --> STATE_CONNECTED: NETWORK_CONNECTED

        state STATE_DISCONNECTED_IDLE {
            STATE_DISCONNECTED_IDLE --> STATE_DISCONNECTED_SEARCHING_TN: NETWORK_CONNECT_TN
            STATE_DISCONNECTED_IDLE --> STATE_DISCONNECTED_NTN_SEARCH: NETWORK_CONNECT_NTN
        }

        state STATE_DISCONNECTED_SEARCHING_TN {
            STATE_DISCONNECTED_SEARCHING_TN : entry / start_search_tn()
            STATE_DISCONNECTED_SEARCHING_TN --> STATE_DISCONNECTED_IDLE: NETWORK_SEARCH_STOP / network_disconnect()
        }

        state STATE_DISCONNECTED_WAITING_FOR_LEO {
            STATE_DISCONNECTED_WAITING_FOR_LEO : entry / periodic_tn_search_timer_start()
            STATE_DISCONNECTED_WAITING_FOR_LEO : exit / periodic_tn_search_timer_cancel()
            STATE_DISCONNECTED_WAITING_FOR_LEO --> STATE_DISCONNECTED_SEARCHING_TN: PERIODIC_TN_SEARCH
        }

        state STATE_DISCONNECTED_NTN_SEARCH {
            [*] --> STATE_NTN_SEARCH_PREPARE

            STATE_DISCONNECTED_NTN_SEARCH : entry / set NTN sys mode
            STATE_DISCONNECTED_NTN_SEARCH --> STATE_DISCONNECTED_IDLE: NETWORK_NTN_NO_SUITABLE_CELL
            STATE_DISCONNECTED_NTN_SEARCH --> STATE_NTN_SEARCH_GEO: NTN_SEARCH_GEO_START

            state STATE_NTN_SEARCH_PREPARE {
                STATE_NTN_SEARCH_PREPARE : NTN_LOCATION_NEEDED / send NETWORK_LOCATION_NEEDED
                STATE_NTN_SEARCH_PREPARE : NETWORK_LOCATION_DATA / ntn_location_set(), estimate_next_pass()
                STATE_NTN_SEARCH_PREPARE : NETWORK_LOCATION_FAILED / start_geo_or_maybe_reset()

                STATE_NTN_SEARCH_PREPARE --> STATE_NTN_SEARCH_LEO: NTN_LEO_SATELLITE_PASS_UPCOMING
                STATE_NTN_SEARCH_PREPARE --> STATE_DISCONNECTED_WAITING_FOR_LEO: NTN_WAIT_FOR_SATELLITE_PASS / leo_satellite_search_timer_start()
            }

            state STATE_NTN_SEARCH_LEO {
                STATE_NTN_SEARCH_LEO : entry / run_sgp4(); start_leo_search()
            }

            state STATE_NTN_SEARCH_GEO {
                STATE_NTN_SEARCH_GEO : entry / start_geo_search()
            }
        }
    }

    state STATE_CONNECTED {
        STATE_CONNECTED : entry / leo_satellite_search_timer_cancel()
        STATE_CONNECTED : NETWORK_TLE_DATA / store_tle_data()

        STATE_CONNECTED --> STATE_DISCONNECTING: NETWORK_DISCONNECT
    }

    state STATE_DISCONNECTING {
        STATE_DISCONNECTING : entry / network_disconnect()
        STATE_DISCONNECTING --> STATE_DISCONNECTED_IDLE: NETWORK_DISCONNECTED
    }
}

@enduml
