@startuml
state STATE_RUNNING

[*] --> STATE_RUNNING

STATE_RUNNING --> STATE_DISCONNECTED: NETWORK_DISCONNECTED
STATE_RUNNING --> STATE_DISCONNECTED_IDLE: NETWORK_UICC_FAILURE

state STATE_RUNNING {
    state STATE_DISCONNECTED
    state STATE_CONNECTED
    state STATE_DISCONNECTING

    [*] --> STATE_DISCONNECTED

    STATE_DISCONNECTED --> STATE_CONNECTED: NETWORK_CONNECTED
    STATE_CONNECTED --> STATE_DISCONNECTING: NETWORK_DISCONNECT
    STATE_DISCONNECTING --> STATE_DISCONNECTED_IDLE: NETWORK_DISCONNECTED

    state STATE_DISCONNECTED {
        state STATE_DISCONNECTED_IDLE
        state STATE_DISCONNECTED_SEARCHING

        [*] --> STATE_DISCONNECTED_SEARCHING : CONFIG_APP_NETWORK_SEARCH_NETWORK_ON_STARTUP
        [*] --> STATE_DISCONNECTED_IDLE : not CONFIG_APP_NETWORK_SEARCH_NETWORK_ON_STARTUP

        STATE_DISCONNECTED_SEARCHING --> STATE_DISCONNECTED_IDLE: NETWORK_SEARCH_STOP || NETWORK_DISCONNECT
        STATE_DISCONNECTED_IDLE --> STATE_DISCONNECTED_SEARCHING: NETWORK_CONNECT
    }
}
@enduml
