@startuml
[*] --> STATE_WAITING_FOR_MODEM_INIT

state STATE_WAITING_FOR_MODEM_INIT {
    STATE_WAITING_FOR_MODEM_INIT : Waiting for modem initialization
}

STATE_WAITING_FOR_MODEM_INIT --> STATE_RUNNING : POWER_PRIV_MODEM_INITIALIZED

state STATE_RUNNING {
    STATE_RUNNING : POWER_BATTERY_PERCENTAGE_SAMPLE_REQUEST / sample()
}
@enduml
