@startuml
[*] --> STATE_RUNNING

state STATE_RUNNING {
    state STATE_PASSTHROUGH
    state STATE_BUFFER

    [*] --> STATE_BUFFER : CONFIG_APP_STORAGE_INITIAL_MODE_BUFFER
    [*] --> STATE_PASSTHROUGH : CONFIG_APP_STORAGE_INITIAL_MODE_PASSTHROUGH

    STATE_PASSTHROUGH --> STATE_BUFFER_IDLE: STORAGE_MODE_BUFFER_REQUEST
    STATE_BUFFER_IDLE --> STATE_PASSTHROUGH: STORAGE_MODE_PASSTHROUGH_REQUEST

    state STATE_BUFFER {
        state STATE_BUFFER_IDLE
        state STATE_BUFFER_PIPE_ACTIVE

        [*] --> STATE_BUFFER_IDLE

        STATE_BUFFER_IDLE --> STATE_BUFFER_PIPE_ACTIVE: STORAGE_BATCH_REQUEST
        STATE_BUFFER_PIPE_ACTIVE --> STATE_BUFFER_IDLE: STORAGE_BATCH_CLOSE || STORAGE_BATCH_SESSION_TIMEOUT
    }
}
@enduml
